module Version ( versionStr,
                 progName ) where

import Data.Version (showVersion)

import Paths_vidmerge (version) -- generated by Cabal

progName :: [Char]
progName = "vidmerge"

versionStr :: [Char]
versionStr = progName ++ " version " ++ showVersion version
